### ISSUE TITLE
Add `eslint-plugin-decorator-position`

### ISSUE THREAD

**Issue by Bosseskompis** [gajus/eslint-config-canonical#41]
Thoughts on adding a rule for decorator position? Doesn't necessarily have to be [eslint-plugin-decorator-position](https://github.com/NullVoxPopuli/eslint-plugin-decorator-position)

**Comment by gajus** [comment]
Not keen on adding a whole dependency just for one plugin. However, as an alternative, would you be open to contribute it to https://github.com/gajus/eslint-plugin-canonical ?

`eslint-plugin-canonical` is an unopinionated ESLint plugin that encourages community to add their own ESLint rules instead of releasing new packages just to publish a single rule.

**Comment by gajus** [comment]
Suggesting porting @NullVoxPopuli rule to `eslint-plugin-canonical` if you'd like it as part of the rulset.

**Comment by NullVoxPopuli** [comment]
something wrong with the dependency? I'm generally anti code duplication for the sake of "no dependencies"

**Comment by gajus** [comment]
It is not about duplicate code – it is about that all of these single-rule packages becoming unmaintained the moment the maintainer loses interest in that particular rule or simply not being active enough to keep the package up to date. The whole reason [eslint-plugin-canonical](https://github.com/gajus/eslint-plugin-canonical) came into existence was because a few packages were lagging behind important updates.

**Comment by gajus** [comment]
But I am happy to add anyone with a track record of open-source work to maintain `eslint-plugin-canonical`.

**Comment by NullVoxPopuli** [comment]
That's fair. tbh, my hope is that once decorators move to Stage 4, prettier will take over responsibility of the type of formatting my package does
